// src/init.ts
// `thebashway init` — the plug-and-play scaffolder. Detects how a repo builds and
// tests itself, writes a starter thebashway.config.ts with that chain filled in,
// creates the local learning store, and checks prerequisites. Idempotent: re-running
// never clobbers an existing config.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import type { VerifyCheck } from "./binding";

export type Runner = "bun" | "pnpm" | "npm";

export interface ProjectDetection {
  runner: Runner;
  isNext: boolean;
  chain: VerifyCheck[];
}

function detectRunner(dir: string): Runner {
  if (existsSync(join(dir, "bun.lock")) || existsSync(join(dir, "bun.lockb"))) return "bun";
  if (existsSync(join(dir, "pnpm-lock.yaml"))) return "pnpm";
  return "npm";
}

/** `<runner> exec <bin> <args>` form (for running a binary like tsc). */
function execCmd(runner: Runner, bin: string, ...args: string[]): string[] {
  if (runner === "bun") return ["bunx", bin, ...args];
  if (runner === "pnpm") return ["pnpm", "exec", bin, ...args];
  return ["npx", bin, ...args];
}

/** `<runner> run <script>` form (for a package.json script). */
function runScript(runner: Runner, script: string): string[] {
  if (runner === "bun") return ["bun", "run", script];
  return [runner, "run", script];
}

/**
 * Inspect a repo and propose a verify chain: typecheck (if a tsconfig is present),
 * then test, then build (whichever package.json scripts exist), in that order.
 */
export async function detectProject(dir: string): Promise<ProjectDetection> {
  const runner = detectRunner(dir);
  let scripts: Record<string, string> = {};
  const pkgPath = join(dir, "package.json");
  if (existsSync(pkgPath)) {
    try {
      scripts = JSON.parse(readFileSync(pkgPath, "utf8")).scripts ?? {};
    } catch {
      scripts = {};
    }
  }
  const hasTsconfig = existsSync(join(dir, "tsconfig.json"));
  const isNext = ["next.config.js", "next.config.mjs", "next.config.ts"].some((f) =>
    existsSync(join(dir, f)),
  );

  const chain: VerifyCheck[] = [];
  if (hasTsconfig) chain.push({ name: "typecheck", cmd: execCmd(runner, "tsc", "--noEmit") });
  if (scripts.test) chain.push({ name: "test", cmd: runScript(runner, "test") });
  if (scripts.build) chain.push({ name: "build", cmd: runScript(runner, "build") });

  return { runner, isNext, chain };
}

function configTemplate(detect: ProjectDetection, globalLessons: string | null): string {
  const chainLines = detect.chain
    .map((c) => `        { name: ${JSON.stringify(c.name)}, cmd: ${JSON.stringify(c.cmd)} },`)
    .join("\n");
  return `// thebashway.config.ts — generated by \`thebashway init\`. Edit freely.
import { defineThebashway } from "thebashway/binding";

export default defineThebashway({
  repoRoot: import.meta.dir,
  defaultSurface: "app",
  surfaces: {
    app: {
      dir: ".",
      role: "The application — the default home for new features in this repo.",
      chain: [
${chainLines || "        // No build/test scripts detected — add your verify commands here."}
      ],${detect.isNext ? "\n      needsRealInstall: true, // Next/Turbopack: a worktree needs a real install, not a symlink" : ""}
    },
  },
  rails: {
    // A task whose text or files match these is set aside for your approval — the
    // engine never sends, deletes, or deploys to production on its own.
    territoryGlobs: [],
    keywords: /\\b(?:send|email|delete|drop|deploy|publish|purge|wipe|cancel)\\b/i,
  },
  learning: {
    global: ${globalLessons ? JSON.stringify(globalLessons) : "null"},
    local: ".thebashway/lessons.md",
    decisions: ".thebashway/decisions.md",
  },
});
`;
}

const LESSONS_SEED = "# Build lessons (this repo)\n\n## Active\n\n## Graduated\n";
const DECISIONS_SEED = "# Intake decisions (this repo)\n\n## Active\n\n## Graduated\n";

function onPath(bin: string): boolean {
  return spawnSync("which", [bin], { encoding: "utf8" }).status === 0;
}

export interface InitResult {
  configPath: string;
  created: boolean; // false when a config already existed (idempotent skip)
  detect: ProjectDetection;
  prereqs: { claude: boolean; git: boolean; cleanTree: boolean };
}

export async function runInit(
  dir: string,
  opts?: { globalLessons?: string | null },
): Promise<InitResult> {
  const detect = await detectProject(dir);

  const configPath = join(dir, "thebashway.config.ts");
  let created = false;
  if (!existsSync(configPath)) {
    writeFileSync(configPath, configTemplate(detect, opts?.globalLessons ?? null), "utf8");
    created = true;
  }

  const storeDir = join(dir, ".thebashway");
  mkdirSync(storeDir, { recursive: true });
  const lessons = join(storeDir, "lessons.md");
  if (!existsSync(lessons)) writeFileSync(lessons, LESSONS_SEED, "utf8");
  const decisions = join(storeDir, "decisions.md");
  if (!existsSync(decisions)) writeFileSync(decisions, DECISIONS_SEED, "utf8");

  const git =
    existsSync(join(dir, ".git")) ||
    spawnSync("git", ["rev-parse", "--is-inside-work-tree"], { cwd: dir }).status === 0;
  const cleanTree =
    git &&
    spawnSync("git", ["status", "--porcelain"], { cwd: dir, encoding: "utf8" }).stdout.trim() === "";

  return { configPath, created, detect, prereqs: { claude: onPath("claude"), git, cleanTree } };
}

/** A short, friendly post-init message (or what's missing). */
export function initMessage(r: InitResult): string {
  const lines: string[] = [];
  lines.push(r.created ? `Wrote ${r.configPath}` : `Kept your existing ${r.configPath}`);
  lines.push(`Detected: ${r.detect.runner}${r.detect.isNext ? " + Next.js" : ""}, chain = [${r.detect.chain.map((c) => c.name).join(", ") || "none — edit the config"}]`);
  if (!r.prereqs.claude) lines.push(`! The \`claude\` command is not on your PATH — install it before running build/fix.`);
  if (!r.prereqs.git) lines.push(`! This folder is not a git repo — run \`git init\` first.`);
  if (r.prereqs.claude && r.prereqs.git) {
    lines.push(`You're ready. Try:  thebashway fix .`);
  }
  return lines.join("\n");
}
